In [1]:
import pandas as pd
import numpy as np
from scipy.stats.mstats import gmean

In [2]:
import os
 
path_dir = 'C:/Users/user/Desktop/금융콘테스트/AHP/'
 
file_list = os.listdir(path_dir)[2:]
file_list

['강남구이_group.csv',
 '강남국탕_group.csv',
 '강남면류_group.csv',
 '강남백반_group.csv',
 '강남야식_group.csv',
 '강남양식_group.csv',
 '강남일식_group.csv',
 '강남초밥_group.csv',
 '강남횟집_group.csv',
 '마포구이_group.csv',
 '마포국탕_group.csv',
 '마포면류_group.csv',
 '마포백반_group.csv',
 '마포야식_group.csv',
 '마포양식_group.csv',
 '마포일식_group.csv',
 '마포초밥_group.csv',
 '마포횟집_group.csv']

In [37]:
def get_ahp_weight(csv_name):
    df = pd.read_csv(csv_name)
    positive = list(df['sentimental_score_positive'])[:-1]
    label = list(df['topic_label'])[:-1]
    a,b,c,d,e,f = positive[0], positive[1], positive[2], positive[3], positive[4], positive[5]
    end_list = [a,b,c,d,e,f] 
    print(len(positive),'개의 토픽 존재')
    if len(positive)>6:
        g = positive[6]
        end_list.append(g)
    if len(positive)>7:
        h = positive[7]
        end_list.append(h)
    if len(positive)>8:
        i = positive[8]
        end_list.append(i)
    if len(positive)>9:
        j = positive[9]
        end_list.append(j)
    if len(positive)>10:
        k = positive[10]
        end_list.append(k)
    if len(positive)>11:
        l = positive[11]
        end_list.append(l)
    if len(positive)>12:
        m = positive[12]
        end_list.append(m)
    if len(positive)>13:
        n = positive[13]
        end_list.append(n)
    if len(positive)>14:
        o = positive[14]
        end_list.append(o)
    #print(end_list)
    final_comp_matrix = comp_matrix_compute(end_list)
    col_sums =  final_comp_matrix.sum(axis=0) # 열의 합 print(‘열의 합 : {}'.format(col_sums)) 
    np02 =  final_comp_matrix/col_sums # 정규화(동일한 열에 있는 col_sumns의 값으로 나눠줍니다.) 
    #print('정규화 : {}'.format(np02))
    row_avg = np02.mean(axis=1) # 속성별 중요도, 가중치(mean(axis=1)은 행의 평균을 계산합니다.) 
    print('가중치 : {}'.format(row_avg))
    
    topic_weight = pd.DataFrame({'topic label': label ,'weight':row_avg})
    new_filename = csv_name + 'ahp_result.csv'
    topic_weight.to_csv(new_filename, index=False)
    return topic_weight

In [38]:
def comp_matrix_compute(positive):
    a,b,c,d,e,f = positive[0], positive[1], positive[2], positive[3], positive[4], positive[5]
    # 비교행렬
    if len(positive)==6: 
        pair_comp_matrix_6 = np.array([[a/a, a/b, a/c, a/d, a/e, a/f], 
                                       [b/a, b/b, b/c, b/d, b/e, b/f],
                                       [c/a, c/b, c/c, c/d, c/e, c/f],
                                       [d/a, d/b, d/c, d/d, d/e, d/f],
                                       [e/a, e/b, e/c, e/d, e/e, e/f],
                                       [f/a, f/b, f/c, f/d, f/e, f/f]])
        comp_matrix = pair_comp_matrix_6
        
    if len(positive)==7:
        g = positive[6]
        pair_comp_matrix_7 = np.array([[a/a, a/b, a/c, a/d, a/e, a/f, a/g],
                                       [b/a, b/b, b/c, b/d, b/e, b/f, b/g],
                                       [c/a, c/b, c/c, c/d, c/e, c/f, c/g],
                                       [d/a, d/b, d/c, d/d, d/e, d/f, d/g],
                                       [e/a, e/b, e/c, e/d, e/e, e/f, e/g],
                                       [f/a, f/b, f/c, f/d, f/e, f/f, f/g],
                                       [g/a, g/b, g/c, g/d, g/e, g/f, g/g]])
        comp_matrix = pair_comp_matrix_7
        
    if len(positive)==8:
        g, h = positive[6], positive[7]
        pair_comp_matrix_8 = np.array([[a/a, a/b, a/c, a/d, a/e, a/f, a/g, a/h],
                                       [b/a, b/b, b/c, b/d, b/e, b/f, b/g, b/h],
                                       [c/a, c/b, c/c, c/d, c/e, c/f, c/g, c/h],
                                       [d/a, d/b, d/c, d/d, d/e, d/f, d/g, d/h],
                                       [e/a, e/b, e/c, e/d, e/e, e/f, e/g, e/h],
                                       [f/a, f/b, f/c, f/d, f/e, f/f, f/g, f/h],
                                       [g/a, g/b, g/c, g/d, g/e, g/f, g/g, g/h],
                                       [h/a, h/b, h/c, h/d, h/e, h/f, h/g, h/h]])
        comp_matrix = pair_comp_matrix_8
    
    if len(positive)==9:
        g, h, i = positive[6], positive[7], positive[8]
        pair_comp_matrix_9 = np.array([[a/a, a/b, a/c, a/d, a/e, a/f, a/g, a/h, a/i],
                                       [b/a, b/b, b/c, b/d, b/e, b/f, b/g, b/h, b/i],
                                       [c/a, c/b, c/c, c/d, c/e, c/f, c/g, c/h, c/i],
                                       [d/a, d/b, d/c, d/d, d/e, d/f, d/g, d/h, d/i],
                                       [e/a, e/b, e/c, e/d, e/e, e/f, e/g, e/h, e/i],
                                       [f/a, f/b, f/c, f/d, f/e, f/f, f/g, f/h, f/i],
                                       [g/a, g/b, g/c, g/d, g/e, g/f, g/g, g/h, g/i],
                                       [h/a, h/b, h/c, h/d, h/e, h/f, h/g, h/h, h/i],
                                       [i/a, i/b, i/c, i/d, i/e, i/f, i/g, i/h, i/i]])
        comp_matrix = pair_comp_matrix_9
        
    if len(positive)==10:
        g, h, i, j = positive[6], positive[7], positive[8], positive[9]
        pair_comp_matrix_10 = np.array([[a/a, a/b, a/c, a/d, a/e, a/f, a/g, a/h, a/i, a/j], 
                                        [b/a, b/b, b/c, b/d, b/e, b/f, b/g, b/h, b/i, b/j],
                                        [c/a, c/b, c/c, c/d, c/e, c/f, c/g, c/h, c/i, c/j],
                                        [d/a, d/b, d/c, d/d, d/e, d/f, d/g, d/h, d/i, d/j],
                                        [e/a, e/b, e/c, e/d, e/e, e/f, e/g, e/h, e/i, e/j],
                                        [f/a, f/b, f/c, f/d, f/e, f/f, f/g, f/h, f/i, f/j],
                                        [g/a, g/b, g/c, g/d, g/e, g/f, g/g, g/h, g/i, g/j],
                                        [h/a, h/b, h/c, h/d, h/e, h/f, h/g, h/h, h/i, h/j],
                                        [i/a, i/b, i/c, i/d, i/e, i/f, i/g, i/h, i/i, i/j],
                                        [j/a, j/b, j/c, j/d, j/e, j/f, j/g, j/h, j/i, j/j]])
        comp_matrix = pair_comp_matrix_10
        
    if len(positive)==11:
        g, h, i, j, k = positive[6], positive[7], positive[8], positive[9], positive[10]
        pair_comp_matrix_11 = np.array([[a/a, a/b, a/c, a/d, a/e, a/f, a/g, a/h, a/i, a/j, a/k], 
                                        [b/a, b/b, b/c, b/d, b/e, b/f, b/g, b/h, b/i, b/j, b/k],
                                        [c/a, c/b, c/c, c/d, c/e, c/f, c/g, c/h, c/i, c/j, c/k],
                                        [d/a, d/b, d/c, d/d, d/e, d/f, d/g, d/h, d/i, d/j, d/k],
                                        [e/a, e/b, e/c, e/d, e/e, e/f, e/g, e/h, e/i, e/j, e/k],
                                        [f/a, f/b, f/c, f/d, f/e, f/f, f/g, f/h, f/i, f/j, f/k],
                                        [g/a, g/b, g/c, g/d, g/e, g/f, g/g, g/h, g/i, g/j, g/k],
                                        [h/a, h/b, h/c, h/d, h/e, h/f, h/g, h/h, h/i, h/j, h/k],
                                        [i/a, i/b, i/c, i/d, i/e, i/f, i/g, i/h, i/i, i/j, i/k],
                                        [j/a, j/b, j/c, j/d, j/e, j/f, j/g, j/h, j/i, j/j, j/k],
                                        [k/a, k/b, k/c, k/d, k/e, k/f, k/g, k/h, k/i, k/j, k/k]])
        comp_matrix = pair_comp_matrix_11
        
    if len(positive)==12:
        g, h, i, j, k, l = positive[6], positive[7], positive[8], positive[9], positive[10], positive[11]
        pair_comp_matrix_12 = np.array([[a/a, a/b, a/c, a/d, a/e, a/f, a/g, a/h, a/i, a/j, a/k, a/l], 
                                        [b/a, b/b, b/c, b/d, b/e, b/f, b/g, b/h, b/i, b/j, b/k, b/l],
                                        [c/a, c/b, c/c, c/d, c/e, c/f, c/g, c/h, c/i, c/j, c/k, c/l],
                                        [d/a, d/b, d/c, d/d, d/e, d/f, d/g, d/h, d/i, d/j, d/k, d/l],
                                        [e/a, e/b, e/c, e/d, e/e, e/f, e/g, e/h, e/i, e/j, e/k, e/l],
                                        [f/a, f/b, f/c, f/d, f/e, f/f, f/g, f/h, f/i, f/j, f/k, f/l],
                                        [g/a, g/b, g/c, g/d, g/e, g/f, g/g, g/h, g/i, g/j, g/k, g/l],
                                        [h/a, h/b, h/c, h/d, h/e, h/f, h/g, h/h, h/i, h/j, h/k, h/l],
                                        [i/a, i/b, i/c, i/d, i/e, i/f, i/g, i/h, i/i, i/j, i/k, i/l],
                                        [j/a, j/b, j/c, j/d, j/e, j/f, j/g, j/h, j/i, j/j, j/k, j/l],
                                        [k/a, k/b, k/c, k/d, k/e, k/f, k/g, k/h, k/i, k/j, k/k, k/l],
                                        [l/a, l/b, l/c, l/d, l/e, l/f, l/g, l/h, l/i, l/j, l/k, l/l]])
        comp_matrix = pair_comp_matrix_12
        
    if len(positive)==13:
        g, h, i, j, k, l, m = positive[6], positive[7], positive[8], positive[9], positive[10], positive[11], positive[12]
        pair_comp_matrix_13 = np.array([[a/a, a/b, a/c, a/d, a/e, a/f, a/g, a/h, a/i, a/j, a/k, a/l, a/m], 
                                        [b/a, b/b, b/c, b/d, b/e, b/f, b/g, b/h, b/i, b/j, b/k, b/l, b/m],
                                        [c/a, c/b, c/c, c/d, c/e, c/f, c/g, c/h, c/i, c/j, c/k, c/l, c/m],
                                        [d/a, d/b, d/c, d/d, d/e, d/f, d/g, d/h, d/i, d/j, d/k, d/l, d/m],
                                        [e/a, e/b, e/c, e/d, e/e, e/f, e/g, e/h, e/i, e/j, e/k, e/l, e/m],
                                        [f/a, f/b, f/c, f/d, f/e, f/f, f/g, f/h, f/i, f/j, f/k, f/l, f/m],
                                        [g/a, g/b, g/c, g/d, g/e, g/f, g/g, g/h, g/i, g/j, g/k, g/l, g/m],
                                        [h/a, h/b, h/c, h/d, h/e, h/f, h/g, h/h, h/i, h/j, h/k, h/l, h/m],
                                        [i/a, i/b, i/c, i/d, i/e, i/f, i/g, i/h, i/i, i/j, i/k, i/l, i/m],
                                        [j/a, j/b, j/c, j/d, j/e, j/f, j/g, j/h, j/i, j/j, j/k, j/l, j/m],
                                        [k/a, k/b, k/c, k/d, k/e, k/f, k/g, k/h, k/i, k/j, k/k, k/l, k/m],
                                        [l/a, l/b, l/c, l/d, l/e, l/f, l/g, l/h, l/i, l/j, l/k, l/l, l/m],
                                        [m/a, m/b, m/c, m/d, m/e, m/f, m/g, m/h, m/i, m/j, m/k, m/l, m/m]])
        comp_matrix = pair_comp_matrix_13
    
    if len(positive)==14:
        g, h, i, j, k, l, m, n = positive[6], positive[7], positive[8], positive[9], positive[10], positive[11], positive[12], positive[13]
        pair_comp_matrix_14 = np.array([[a/a, a/b, a/c, a/d, a/e, a/f, a/g, a/h, a/i, a/j, a/k, a/l, a/m, a/n], 
                                         [b/a, b/b, b/c, b/d, b/e, b/f, b/g, b/h, b/i, b/j, b/k, b/l, b/m, b/n],
                                         [c/a, c/b, c/c, c/d, c/e, c/f, c/g, c/h, c/i, c/j, c/k, c/l, c/m, c/n],
                                         [d/a, d/b, d/c, d/d, d/e, d/f, d/g, d/h, d/i, d/j, d/k, d/l, d/m, d/n],
                                         [e/a, e/b, e/c, e/d, e/e, e/f, e/g, e/h, e/i, e/j, e/k, e/l, e/m, e/n],
                                         [f/a, f/b, f/c, f/d, f/e, f/f, f/g, f/h, f/i, f/j, f/k, f/l, f/m, f/n],
                                         [g/a, g/b, g/c, g/d, g/e, g/f, g/g, g/h, g/i, g/j, g/k, g/l, g/m, g/n],
                                         [h/a, h/b, h/c, h/d, h/e, h/f, h/g, h/h, h/i, h/j, h/k, h/l, h/m, h/n],
                                         [i/a, i/b, i/c, i/d, i/e, i/f, i/g, i/h, i/i, i/j, i/k, i/l, i/m, i/n],
                                         [j/a, j/b, j/c, j/d, j/e, j/f, j/g, j/h, j/i, j/j, j/k, j/l, j/m, j/n],
                                         [k/a, k/b, k/c, k/d, k/e, k/f, k/g, k/h, k/i, k/j, k/k, k/l, k/m, k/n],
                                         [l/a, l/b, l/c, l/d, l/e, l/f, l/g, l/h, l/i, l/j, l/k, l/l, l/m, l/n],
                                         [m/a, m/b, m/c, m/d, m/e, m/f, m/g, m/h, m/i, m/j, m/k, m/l, m/m, m/n],
                                         [n/a, n/b, n/c, n/d, n/e, n/f, n/g, n/h, n/i, n/j, n/k, n/l, n/m, n/n]])
        comp_matrix = pair_comp_matrix_14
    
    if len(positive)==15:
        g, h, i, j, k, l, m, n, o = positive[6], positive[7], positive[8], positive[9], positive[10], positive[11], positive[12], positive[13], positive[14]
        pair_comp_matrix_15 = np.array([[a/a, a/b, a/c, a/d, a/e, a/f, a/g, a/h, a/i, a/j, a/k, a/l, a/m, a/n, a/o], 
                                        [b/a, b/b, b/c, b/d, b/e, b/f, b/g, b/h, b/i, b/j, b/k, b/l, b/m, b/n, b/o],
                                        [c/a, c/b, c/c, c/d, c/e, c/f, c/g, c/h, c/i, c/j, c/k, c/l, c/m, c/n, c/o],
                                        [d/a, d/b, d/c, d/d, d/e, d/f, d/g, d/h, d/i, d/j, d/k, d/l, d/m, d/n, d/o],
                                        [e/a, e/b, e/c, e/d, e/e, e/f, e/g, e/h, e/i, e/j, e/k, e/l, e/m, e/n, e/o],
                                        [f/a, f/b, f/c, f/d, f/e, f/f, f/g, f/h, f/i, f/j, f/k, f/l, f/m, f/n, f/o],
                                        [g/a, g/b, g/c, g/d, g/e, g/f, g/g, g/h, g/i, g/j, g/k, g/l, g/m, g/n, g/o],
                                        [h/a, h/b, h/c, h/d, h/e, h/f, h/g, h/h, h/i, h/j, h/k, h/l, h/m, h/n, h/o],
                                        [i/a, i/b, i/c, i/d, i/e, i/f, i/g, i/h, i/i, i/j, i/k, i/l, i/m, i/n, i/o],
                                        [j/a, j/b, j/c, j/d, j/e, j/f, j/g, j/h, j/i, j/j, j/k, j/l, j/m, j/n, j/o],
                                        [k/a, k/b, k/c, k/d, k/e, k/f, k/g, k/h, k/i, k/j, k/k, k/l, k/m, k/n, k/o],
                                        [l/a, l/b, l/c, l/d, l/e, l/f, l/g, l/h, l/i, l/j, l/k, l/l, l/m, l/n, l/o],
                                        [m/a, m/b, m/c, m/d, m/e, m/f, m/g, m/h, m/i, m/j, m/k, m/l, m/m, m/n, m/o],
                                        [n/a, n/b, n/c, n/d, n/e, n/f, n/g, n/h, n/i, n/j, n/k, n/l, n/m, n/n, n/o],
                                        [o/a, o/b, o/c, o/d, o/e, o/f, o/g, o/h, o/i, o/j, o/k, o/l, o/m, o/n, o/o]])
        comp_matrix = pair_comp_matrix_15
    print('쌍대비교 행렬 크기 : ',comp_matrix.shape)
    #print(comp_matrix)
    return comp_matrix

In [39]:
get_ahp_weight('강남구이_group.csv')

14 개의 토픽 존재
쌍대비교 행렬 크기 :  (14, 14)
가중치 : [0.06065965 0.05855095 0.09465828 0.10299108 0.05955626 0.06164316
 0.07362437 0.04909429 0.07376859 0.07560936 0.06985663 0.07822767
 0.07588111 0.06587859]

    topic label    weight
0             0  0.060660
1             1  0.058551
2             2  0.094658
3             3  0.102991
4             4  0.059556
5             5  0.061643
6             6  0.073624
7             7  0.049094
8             8  0.073769
9             9  0.075609
10           10  0.069857
11           11  0.078228
12           12  0.075881
13           13  0.065879

In [40]:
get_ahp_weight('강남국탕_group.csv')

10 개의 토픽 존재
쌍대비교 행렬 크기 :  (10, 10)
가중치 : [0.13338445 0.09533766 0.08725618 0.10672375 0.09196855 0.08083861
 0.09658364 0.12214481 0.07757264 0.1081897 ]

   topic label    weight
0            0  0.133384
1            1  0.095338
2            2  0.087256
3            3  0.106724
4            4  0.091969
5            5  0.080839
6            6  0.096584
7            7  0.122145
8            8  0.077573
9            9  0.108190

In [43]:
get_ahp_weight('강남면류_group.csv')

9 개의 토픽 존재
쌍대비교 행렬 크기 :  (9, 9)
가중치 : [0.12539518 0.10720334 0.11796406 0.11212113 0.07811458 0.10173377
 0.09596682 0.13683296 0.12466817]

   topic label    weight
0            0  0.125395
1            1  0.107203
2            2  0.117964
3            3  0.112121
4            4  0.078115
5            5  0.101734
6            6  0.095967
7            7  0.136833
8            8  0.124668

In [44]:
get_ahp_weight('강남백반_group.csv')

8 개의 토픽 존재
쌍대비교 행렬 크기 :  (8, 8)
가중치 : [0.11704278 0.15492573 0.0966386  0.13379606 0.12762351 0.109847
 0.1412233  0.11890302]

   topic label    weight
0            0  0.117043
1            1  0.154926
2            2  0.096639
3            3  0.133796
4            4  0.127624
5            5  0.109847
6            6  0.141223
7            7  0.118903

In [45]:
get_ahp_weight('강남야식_group.csv')

11 개의 토픽 존재
쌍대비교 행렬 크기 :  (11, 11)
가중치 : [0.08386723 0.08739768 0.09038343 0.09255475 0.09294769 0.09681402
 0.07230143 0.11305847 0.07501837 0.10552596 0.09013097]

    topic label    weight
0             0  0.083867
1             1  0.087398
2             2  0.090383
3             3  0.092555
4             4  0.092948
5             5  0.096814
6             6  0.072301
7             7  0.113058
8             8  0.075018
9             9  0.105526
10           10  0.090131

In [46]:
get_ahp_weight('강남양식_group.csv')

11 개의 토픽 존재
쌍대비교 행렬 크기 :  (11, 11)
가중치 : [0.0986575  0.08853393 0.07583913 0.08781518 0.06113336 0.08925298
 0.11217804 0.0974527  0.0942072  0.07922702 0.11570294]

    topic label    weight
0             0  0.098657
1             1  0.088534
2             2  0.075839
3             3  0.087815
4             4  0.061133
5             5  0.089253
6             6  0.112178
7             7  0.097453
8             8  0.094207
9             9  0.079227
10           10  0.115703

In [47]:
get_ahp_weight('강남일식_group.csv')

8 개의 토픽 존재
쌍대비교 행렬 크기 :  (8, 8)
가중치 : [0.1391933  0.12782138 0.10993342 0.09745156 0.12069281 0.15179913
 0.12016012 0.13294827]

   topic label    weight
0            0  0.139193
1            1  0.127821
2            2  0.109933
3            3  0.097452
4            4  0.120693
5            5  0.151799
6            6  0.120160
7            7  0.132948

In [48]:
get_ahp_weight('강남초밥_group.csv')

6 개의 토픽 존재
쌍대비교 행렬 크기 :  (6, 6)
가중치 : [0.15618508 0.16545321 0.21098952 0.17863941 0.12683215 0.16190062]

   topic label    weight
0            0  0.156185
1            1  0.165453
2            2  0.210990
3            3  0.178639
4            4  0.126832
5            5  0.161901

In [49]:
get_ahp_weight('강남횟집_group.csv')

7 개의 토픽 존재
쌍대비교 행렬 크기 :  (7, 7)
가중치 : [0.15398024 0.16371144 0.11053084 0.14961479 0.16074226 0.15050439
 0.11091603]

   topic label    weight
0            0  0.153980
1            1  0.163711
2            2  0.110531
3            3  0.149615
4            4  0.160742
5            5  0.150504
6            6  0.110916

In [50]:
get_ahp_weight('마포구이_group.csv')

9 개의 토픽 존재
쌍대비교 행렬 크기 :  (9, 9)
가중치 : [0.10805447 0.09240476 0.11114048 0.12525111 0.08896893 0.07209229
 0.12893591 0.12911698 0.14403507]

   topic label    weight
0            0  0.108054
1            1  0.092405
2            2  0.111140
3            3  0.125251
4            4  0.088969
5            5  0.072092
6            6  0.128936
7            7  0.129117
8            8  0.144035

In [51]:
get_ahp_weight('마포국탕_group.csv')

10 개의 토픽 존재
쌍대비교 행렬 크기 :  (10, 10)
가중치 : [0.10639968 0.07761192 0.09620098 0.13979386 0.10164148 0.06961096
 0.09422732 0.07605276 0.11571793 0.12274309]

   topic label    weight
0            0  0.106400
1            1  0.077612
2            2  0.096201
3            3  0.139794
4            4  0.101641
5            5  0.069611
6            6  0.094227
7            7  0.076053
8            8  0.115718
9            9  0.122743

In [52]:
get_ahp_weight('마포면류_group.csv')

10 개의 토픽 존재
쌍대비교 행렬 크기 :  (10, 10)
가중치 : [0.08980775 0.08058897 0.08648142 0.10251578 0.09510013 0.10730772
 0.10552783 0.09941846 0.136637   0.09661494]

   topic label    weight
0            0  0.089808
1            1  0.080589
2            2  0.086481
3            3  0.102516
4            4  0.095100
5            5  0.107308
6            6  0.105528
7            7  0.099418
8            8  0.136637
9            9  0.096615

In [53]:
get_ahp_weight('마포백반_group.csv')

9 개의 토픽 존재
쌍대비교 행렬 크기 :  (9, 9)
가중치 : [0.14027225 0.08741015 0.08037155 0.09793804 0.09849122 0.08921709
 0.10981676 0.14813435 0.1483486 ]

   topic label    weight
0            0  0.140272
1            1  0.087410
2            2  0.080372
3            3  0.097938
4            4  0.098491
5            5  0.089217
6            6  0.109817
7            7  0.148134
8            8  0.148349

In [54]:
get_ahp_weight('마포야식_group.csv')

9 개의 토픽 존재
쌍대비교 행렬 크기 :  (9, 9)
가중치 : [0.11342478 0.14426981 0.12087956 0.07426803 0.11448845 0.1078049
 0.09943551 0.1184833  0.10694566]

   topic label    weight
0            0  0.113425
1            1  0.144270
2            2  0.120880
3            3  0.074268
4            4  0.114488
5            5  0.107805
6            6  0.099436
7            7  0.118483
8            8  0.106946

In [55]:
get_ahp_weight('마포양식_group.csv')

9 개의 토픽 존재
쌍대비교 행렬 크기 :  (9, 9)
가중치 : [0.12587523 0.13337031 0.11222635 0.08232495 0.11017551 0.09420714
 0.13152063 0.12998388 0.080316  ]

   topic label    weight
0            0  0.125875
1            1  0.133370
2            2  0.112226
3            3  0.082325
4            4  0.110176
5            5  0.094207
6            6  0.131521
7            7  0.129984
8            8  0.080316

In [56]:
get_ahp_weight('마포일식_group.csv')

6 개의 토픽 존재
쌍대비교 행렬 크기 :  (6, 6)
가중치 : [0.19094378 0.16686784 0.13167718 0.17500327 0.17249067 0.16301726]

   topic label    weight
0            0  0.190944
1            1  0.166868
2            2  0.131677
3            3  0.175003
4            4  0.172491
5            5  0.163017

In [57]:
get_ahp_weight('마포초밥_group.csv')

7 개의 토픽 존재
쌍대비교 행렬 크기 :  (7, 7)
가중치 : [0.14037514 0.15438329 0.14303547 0.1708738  0.12463027 0.13912527
 0.12757676]

   topic label    weight
0            0  0.140375
1            1  0.154383
2            2  0.143035
3            3  0.170874
4            4  0.124630
5            5  0.139125
6            6  0.127577

In [58]:
get_ahp_weight('마포횟집_group.csv')

7 개의 토픽 존재
쌍대비교 행렬 크기 :  (7, 7)
가중치 : [0.15607518 0.13023947 0.13980305 0.13790695 0.11737844 0.17200734
 0.14658957]

   topic label    weight
0            0  0.156075
1            1  0.130239
2            2  0.139803
3            3  0.137907
4            4  0.117378
5            5  0.172007
6            6  0.146590